const PRODUCT_IMAGES = {
  antistatic: 'https://cdn.nafco-online.com/upload/save_image/n92709944_1.jpg',
  antioxidant: 'https://5.imimg.com/data5/SELLER/Default/2026/1/578826151/ZJ/SH/JS/183500820/co-extruded-anti-oxident-pe-film-500x500.png',
  colored: 'https://image.made-in-china.com/202f0j00kLofIDeqbHbB/500-Micron-Black-Color-Packaging-Plastic-Pet-Film-for-Thermoforming.webp',
  blackwhite: 'https://tiimg.tistatic.com/fp/1/008/359/8x14-inch-rectangular-tamper-proof-courier-bags-for-packaging-purpose--827.jpg',
  corona: 'https://www.kuberpolyfilms.com/resources/P4-1.jpeg',
  foodgrade: 'https://image.made-in-china.com/2f0j00BYvoahnyAjgz/Food-Grade-Packaging-Materials-PE-Film-for-Cold-Heat-Sealing.jpg',
  tubes: 'https://www.kuberpolyfilms.com/resources/51.jpg',
  liquid: 'https://img1.exportersindia.com/product_images/bc-full/2024/3/13175332/ldpe-water-1710502364_7340309_2051569.jpeg',
  mulch: 'https://cdn.shopify.com/s/files/1/0722/2059/files/siddhi-plastic-mulching-film-mulching-paper-1000mm-width-4-foot-length-400-meter-file-14666.png?v=1737450468',
  nitrogen: 'https://ecdn6.globalso.com/upload/p/1548/image_other/2025-07/picture-2-40.png',
  shrink: 'https://www.kuberpolyfilms.com/resources/24.jpg',
  retort: 'https://image.made-in-china.com/2f0j00BNOakZhcnQpP/High-Barrier-Resistance-Plastic-Flexbile-Packaging-Retort-Film.jpg',
  lowcof: 'https://ecdn6.globalso.com/upload/p/1548/image_other/2025-07/picture-2-40.png',
  fliptransparent: 'https://www.euphoriapackaging.in/storage/images/1756468762_06_TSB4.jpg',
  flipopaque: 'https://www.euphoriapackaging.in/storage/images/1756468762_06_TSB4.jpg',
  snapdeal: 'https://picknpack.co/wp-content/uploads/2023/11/m15-1024x1024.jpg',
  amazon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzy01HbGDWIlxaK8_xdOGwtQzETuMJ4q471zKQC7qZZg&s=10',
  ajio: 'https://m.media-amazon.com/images/I/51Mknk8FpuL.jpg',
  naaptol: 'https://5.imimg.com/data5/SELLER/Default/2025/6/516337122/AE/EQ/MF/96495776/img20250531115757.jpg',
  custom: 'https://i.etsystatic.com/35838599/r/il/f2d57d/5011666913/il_570xN.5011666913_aa3r.jpg'
};

const products = [
  {id:'anti-static-polyfilm', name:'Anti-Static Polyfilm', tag:'Industrial Film', category:'industrial', imageKey:'antistatic', short:'Static-dissipative film for electronics, appliances and sensitive component packaging.', description:'Specialized polyfilm with anti-static properties to reduce dust attraction and static electricity buildup. Designed for protective packaging around electronics and sensitive equipment.', features:['Static-dissipative properties','Customizable thickness','Excellent clarity','Available in various sizes','Protects sensitive electronics'], uses:'Electronics, computer parts, sensitive equipment'},
  {id:'anti-oxidant-pe-film', name:'Anti-Oxidant PE Film', tag:'Industrial Film', category:'industrial', imageKey:'antioxidant', short:'High-performance polyethylene with antioxidant protection for longer product shelf life.', description:'High-performance polyethylene film with antioxidant additives that help reduce degradation while supporting stable packaging performance over longer storage and distribution cycles.', features:['Oxygen barrier properties','Extended shelf life','Food-safe material options','Flexible yet durable','Customizable thickness'], uses:'Food packaging, pharmaceuticals, sensitive materials'},
  {id:'black-coloured-films', name:'Black & Other Coloured Films', tag:'Specialty Film', category:'specialty', imageKey:'colored', short:'Coloured polyethylene films for light protection, branding and specialized packaging.', description:'Versatile coloured polyethylene films available in black and other colours for specialized packaging requirements where appearance, opacity and light protection matter.', features:['UV protection','Multiple colour options','Consistent coloration','Excellent durability','Custom sizing available'], uses:'Light-sensitive products, branding, specialized packaging'},
  {id:'black-white-courier-film', name:'Black & White Courier Bag Film', tag:'E-commerce Film', category:'ecommerce', imageKey:'blackwhite', short:'Durable black-and-white film designed for secure tamper-evident courier bags.', description:'Black-and-white polyethylene film designed for courier bag conversion, balancing opacity, tear resistance and printability for secure shipping applications.', features:['High tear resistance','Dual-colour structure','Tamper-evident options','Weather resistant','Printable surface'], uses:'E-commerce, logistics, postal services'},
  {id:'corona-ldpe-film', name:'Both Side Corona Treated LDPE Film', tag:'Converter Film', category:'industrial', imageKey:'corona', short:'Corona-treated LDPE film for printing, lamination and coating.', description:'Low-density polyethylene film with corona treatment on both sides to improve surface energy and adhesion for printing, lamination and coating operations.', features:['Superior ink adhesion','Enhanced surface energy','Excellent for lamination','Consistent treatment level','Multiple thickness options'], uses:'Printing, lamination, adhesive applications'},
  {id:'food-grade-lamination-film', name:'Food Grade PE Film for Lamination', tag:'Food Packaging', category:'food', imageKey:'foodgrade', short:'Food-safe PE film engineered for high-quality lamination structures.', description:'Food-grade polyethylene film designed for lamination, offering a strong moisture barrier, excellent transparency and reliable heat seal performance.', features:['Food-safe material options','Moisture barrier','Excellent transparency','Heat-sealable','Puncture resistant'], uses:'Food packaging, beverage packaging, snack packaging'},
  {id:'ldpe-tubes-liner-bags', name:'LDPE Tubes & Liner Bags', tag:'Industrial Packaging', category:'industrial', imageKey:'tubes', short:'Flexible containment solutions for irregular products, bins and bulk handling.', description:'Flexible LDPE tubes and liner bags for industrial and packaging workflows, providing containment, protection and a custom-fit barrier against dust, moisture and leakage.', features:['Customizable dimensions','Leak-proof design','Chemical resistant','Flexible yet strong','Cost-effective solution'], uses:'Industrial packaging, bulk container liners, chemical storage'},
  {id:'liquid-packaging-film', name:'Liquid Packaging Film', tag:'Liquid Packaging', category:'food', imageKey:'liquid', short:'Seal-ready film for water, beverages, sauces and other liquid products.', description:'Specialized polyethylene film designed for liquid packaging applications with strong sealing, puncture resistance and flexible pouch-forming capability.', features:['High moisture barrier','Puncture resistant','Heat-sealable','Chemical resistant','Customizable thickness'], uses:'Beverages, sauces, industrial liquids, chemicals'},
  {id:'mulch-film', name:'Mulch Film', tag:'Agricultural Film', category:'agriculture', imageKey:'mulch', short:'Agricultural polyethylene film for soil coverage, moisture retention and weed suppression.', description:'Agricultural polyethylene film used for soil covering to help manage weeds, conserve moisture and regulate soil temperature around crops.', features:['UV stabilized','Moisture retention','Temperature regulation','Weed suppression','Biodegradable options available'], uses:'Agriculture, horticulture, landscaping'},
  {id:'nitrogen-flush-polyfilm', name:'Nitrogen Flush Polyfilm', tag:'Food Packaging', category:'food', imageKey:'nitrogen', short:'Barrier film for nitrogen-flushed packaging that helps preserve freshness and aroma.', description:'Specialized barrier film designed for nitrogen-flushed packaging applications to reduce oxygen exposure and support longer product freshness.', features:['Excellent gas barrier','Preserves product freshness','Helps prevent oxidation','Supports extended shelf life','Food-safe material options'], uses:'Coffee packaging, snack foods, nuts, dried fruits'},
  {id:'pe-ldpe-shrink-film', name:'PE / LDPE Shrink Film', tag:'Shrink Packaging', category:'industrial', imageKey:'shrink', short:'Heat-shrinkable polyethylene film for tight, secure bundling and protection.', description:'PE/LDPE shrink film that contracts under heat to create a close-fitting package around multipacks, consumer products and industrial bundles.', features:['Excellent shrink properties','High clarity','Puncture resistant','Various thickness options','Customizable shrink ratio'], uses:'Beverage multipacks, consumer products, industrial bundling'},
  {id:'retort-frozen-polyfilm', name:'Retort & Frozen Food Polyfilm', tag:'Food Packaging', category:'food', imageKey:'retort', short:'High-performance film for temperature-intensive retort and frozen applications.', description:'High-performance film designed to maintain package integrity across severe temperature conditions used in retort processing and frozen-food packaging.', features:['Temperature resistant','Excellent barrier properties','Puncture resistant','Maintains flexibility when frozen','Food-safe material options'], uses:'Ready meals, frozen foods, retort processed foods'},
  {id:'low-cof-tobacco', name:'Specialized Low COF Poly – Tobacco Products', tag:'Specialty Film', category:'specialty', imageKey:'lowcof', short:'Low-friction PE film for high-speed tobacco pouch packaging and easy opening.', description:'Specialized polyethylene film with a low coefficient of friction for smoother handling, high-speed packaging and easier pouch opening.', features:['Low friction surface','High-speed packaging compatible','Excellent barrier properties','Consistent quality','Regulatory-ready material options'], uses:'Tobacco products, high-speed packaging lines'},
  {id:'flipkart-transparent', name:'Flipkart Series – Transparent', tag:'Courier Bag', category:'ecommerce', imageKey:'fliptransparent', short:'Transparent courier bags in the TSB0–TSB4 family for branded e-commerce fulfilment.', description:'Transparent polyethylene courier bags designed around common Flipkart shipment formats, with strong seals, clear presentation and tamper-evident construction.', features:['High clarity','Strong seal strength','TSB0–TSB4 sizes','E-commerce focused','Tamper-evident security'], uses:'E-commerce, marketplace fulfilment, online retail'},
  {id:'flipkart-nontransparent', name:'Flipkart Series – Non-Transparent', tag:'Courier Bag', category:'ecommerce', imageKey:'flipopaque', short:'Opaque courier bags in the NSB0–NSB5 family for privacy-first shipping.', description:'Professional opaque courier bags suited to marketplace shipments where privacy, durability and secure closure are priorities.', features:['Opaque privacy layer','Durable construction','NSB0–NSB5 sizes','Weather resistant','Secure closure system'], uses:'E-commerce, secure shipping, marketplace deliveries'},
  {id:'snapdeal-series', name:'Snapdeal Series Courier Bags', tag:'Courier Bag', category:'ecommerce', imageKey:'snapdeal', short:'Standardized courier bag formats for Snapdeal-oriented shipment workflows.', description:'Courier bags available in common e-commerce sizes with strong adhesive closure, tear resistance and water resistance.', features:['Standardized sizes','Strong adhesive closure','Tear-resistant material','Water-resistant','Cost-effective'], uses:'Snapdeal marketplace, e-commerce shipping'},
  {id:'amazon-series', name:'Amazon Series', tag:'Courier Bag', category:'ecommerce', imageKey:'amazon', short:'Marketplace-ready courier bags offered across the NH and NP/NM families.', description:'Premium courier bag formats aligned to common Amazon fulfilment requirements, with multiple size variants and secure closure.', features:['Multiple size variants','Professional finish','Secure closure system','Durable construction','Marketplace-oriented formats'], uses:'Amazon marketplace, e-commerce fulfilment'},
  {id:'ajio-series', name:'AJIO Series Bags', tag:'Courier Bag', category:'ecommerce', imageKey:'ajio', short:'Fashion e-commerce courier bags designed for branded retail delivery.', description:'Fashion-forward courier bags in common dimensions with strong seal strength, professional presentation and moisture resistance.', features:['Fashion-retail optimized','Multiple size options','Strong seal strength','Professional appearance','Moisture resistant'], uses:'Fashion e-commerce, retail fulfilment'},
  {id:'naaptol-series', name:'Naaptol Series Polybags', tag:'Courier Bag', category:'ecommerce', imageKey:'naaptol', short:'Durable tamper-resistant polybags for marketplace and retail delivery.', description:'High-quality polybags focused on secure, durable and tamper-resistant dispatch for e-commerce and retail operations.', features:['Tamper-resistant construction','Durable & tear resistant','Waterproof & lightweight','Custom branding available','E-commerce focused'], uses:'Marketplace shipping, retail delivery, e-commerce'},
  {id:'custom-bag-series', name:'Custom Bag Series', tag:'Custom Packaging', category:'ecommerce', imageKey:'custom', short:'Branded courier bags customized around your artwork, colours, sizing and volumes.', description:'Customizable courier bags for branded shipping programs, with flexible dimensions, brand-specific colours and bulk production options.', features:['Customizable design','Multiple size options','Brand-specific colours','Professional finish','Bulk ordering available'], uses:'Custom e-commerce, branded shipping, retail distribution'}
];

function imageFor(product) { return PRODUCT_IMAGES[product.imageKey] || PRODUCT_IMAGES.colored; }
window.PRODUCTS = products;
window.PRODUCT_IMAGE = imageFor;
